services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=udomdb
      - PGPASSWORD=NDENZA2809
      - PGPORT=5432
      - PORT=5000

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: udomdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LAYSON2809
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  pgdata:
